### PR TITLE
Add mocha tests. Add support for caret (^).

### PR DESCRIPTION
**Pull request by raineorshine**
Thanks for the lib! I'm using this in [npm-check-updates](https://github.com/tjunnone/npm-check-updates) since the "npm" npm module's parsing does not preserve the original operator.

### CODE REVIEW

**Comment by metaraine** [comment]
I added a fix for pre-release versions that contain hyphens. This library is actively used by the [npm-check-updates](/tjunnone/npm-check-updates) project. Would love to see the pull request merged and a new npm package published. Until then, I will continue referencing a reference to the fork.

**Comment by treythomas123** [comment]
This would be convenient to have merged, so that npm-check-updates could depend on it instead of the fork.

**Comment by coolaj86** [comment]
Dang... how did I not see this months ago? merged!

**Comment by treythomas123** [comment]
Great, thanks!

**Pull request merged**
